version: '3'

services:
  # MariaDB service for LinaEE
  linadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: linadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_USER_PW}
      - TZ=${LOC_TZ}
    volumes:
      - /home/numen/linadbsql/linaee.sql:/docker-entrypoint-initdb.d/1.sql
      - /home/numen/linadb:/config
    networks:
      net:
        ipv4_address: 192.168.15.5
    ports:
        - 3305:3306
    restart: unless-stopped

  # Django backend service
  be:
    build:
      context: ./linabe
      dockerfile: Dockerfile
    container_name: linabe
    environment:
      - APP_DEBUG=${APP_DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_USER_PW=${DB_USER_PW}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_WAIT_TIME_OUT=${DB_WAIT_TIME_OUT}
      - DB_WAIT_TIME_EXTRA=${DB_WAIT_TIME_EXTRA}
      - EXTDB1_ENGINE=${EXTDB1_ENGINE}
      - EXTDB1_NAME=${EXTDB1_NAME}
      - EXTDB1_USER=${EXTDB1_USER}
      - EXTDB1_USER_PW=${EXTDB1_USER_PW}
      - EXTDB1_HOST=${EXTDB1_HOST}
      - EXTDB1_PORT=${EXTDB1_PORT}
      - LOC_TZ=${LOC_TZ}
      - LOC_LG=${LOC_LG}
      - TZ=${LOC_TZ}
    volumes:
      - ./linabe:/linabe
    networks:
      net:
        ipv4_address: 192.168.15.4
    ports:
      - 8001:8001
    command: ['./be.sh']
    stop_signal: SIGINT
    depends_on:
      - linadb
    restart: unless-stopped

  # Nuxt frontend service
  fe:
    build:
      context: ./linafe
      dockerfile: Dockerfile
    container_name: linafe
    environment:
      HOST: 0.0.0.0
      TZ: ${LOC_TZ}
      NODE_OPTIONS: --max_old_space_size=8048
    volumes:
      - ./linafe:/linafe
    networks:
      net:
        ipv4_address: 192.168.15.3
    ports:
      - 3005:3005
    command: ['./fe.sh']
    depends_on:
      - be
    restart: unless-stopped

  # Odoo 14
  odooweb:
    image: odoo:14
    container_name: odooweb
    environment:
    - HOST=odoodb
    - USER=${ODOODB_USER}
    - PASSWORD=${ODOODB_PASSWORD}
    volumes:
      - /home/numen/odoo14/webdata:/var/lib/odoo
      - /home/numen/odoo14/config:/etc/odoo
      - /home/numen/odoo14/extra-addons:/mnt/extra-addons
      - /home/numen/odoo14/numen-addons:/mnt/numen-addons
    networks:
      net:
        ipv4_address: 192.168.15.2
    ports:
      - "8069:8069"
    depends_on:
      - odoodb
    restart: unless-stopped

  # PostgresSQL for Odoo
  odoodb:
    image: postgres
    container_name: odoodb
    environment:
      - POSTGRES_DB=${ODOODB_NAME}
      - POSTGRES_PASSWORD=${ODOODB_PASSWORD}
      - POSTGRES_USER=${ODOODB_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /home/numen/odoo14/dbdata:/var/lib/postgresql/data/pgdata
    networks:
      net:
        ipv4_address: 192.168.15.6
    ports:
      - 5439:5439
    restart: unless-stopped

  # Nube Nextcloud 
  nube:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nube
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${LOC_TZ}
      - MYSQL_HOST=${NUBE_DB_HOST}
      - MYSQL_DATABASE=${NUBE_DB_NAME}
      - MYSQL_ROOT_PASSWORD=${NUBE_DB_ROOT_PW}
      - MYSQL_USER=${NUBE_DB_USER}
      - MYSQL_PASSWORD=${NUBE_DB_USER_PW}
    volumes:
      - /home/numen/nube/config:/config
      - /home/numen/nube/data:/data
    networks:
      net:
        ipv4_address: 192.168.15.10
    depends_on:
      - nubedb
    restart: unless-stopped

  # Base de datos MariaDB para la nube
  nubedb:
    image: ghcr.io/linuxserver/mariadb
    container_name: nubedb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${NUBE_DB_ROOT_PW}
      - TZ=${LOC_TZ}
      - MYSQL_DATABASE=${NUBE_DB_NAME}
      - MYSQL_USER=${NUBE_DB_USER}
      - MYSQL_PASSWORD=${NUBE_DB_USER_PW}
    volumes:
      - /home/numen/nube/db:/config
    networks:
      net:
        ipv4_address: 192.168.15.7
    ports:
        - 3307:3306
    restart: unless-stopped

  # Proxies requests to internal services Nginx Reverse Proxy
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${LOC_TZ}
      - URL=${DOMAIN_URL}
      - SUBDOMAINS=${SUBDOMAINS}
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
    volumes:
      - /home/numen/swag:/config
      - /home/numen/nube:/var/www/html
      - ./linabe/static:/static
      - ./linabe/media:/media
    networks:
      net:
        ipv4_address: 192.168.15.11
    ports:
      - 443:443
      - 80:80
    depends_on:
        - be
        - fe
        - odooweb
    restart: unless-stopped

# volumes:
#   odoo-db-data:
#   odoo-web-data:

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.15.0/28