# Generated by Django 3.1.2 on 2020-10-16 00:00

import ckeditor.fields
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único interno para la compañía', max_length=5, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre completo de la compañía', max_length=60, verbose_name='Nombre')),
                ('nombre_corto', models.CharField(blank=True, help_text='Nombre abreviado de la compañía', max_length=30, verbose_name='Nombre Corto')),
                ('ruc', models.CharField(blank=True, default='000000-0-000000', help_text='Registro único de contribuyente', max_length=30, verbose_name='RUC')),
                ('dv', models.CharField(blank=True, default='000', help_text='Dígito verificador', max_length=3, verbose_name='DV')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='E-mail')),
                ('website', models.URLField(blank=True, verbose_name='URL')),
                ('tel1', models.CharField(blank=True, max_length=15, verbose_name='Tel1')),
                ('tel2', models.CharField(blank=True, max_length=15, verbose_name='Tel2')),
                ('fax', models.CharField(blank=True, max_length=15, verbose_name='Fax')),
                ('otros_tels', models.CharField(blank=True, max_length=60, verbose_name='Otros Tels')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('logopath', models.ImageField(blank=True, default='images/no_image.png', upload_to='images', verbose_name='Logo')),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('soporte_idcli', models.CharField(blank=True, default='numencli', max_length=10)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Compañía',
                'verbose_name_plural': 'Compañías',
                'db_table': 'lina_core_cia',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('dni', models.CharField(blank=True, help_text='Documento Nacional de Identidad', max_length=30, verbose_name='DNI')),
                ('direccion', models.CharField(blank=True, max_length=60, verbose_name='Dirección')),
                ('tel1', models.CharField(blank=True, max_length=15, verbose_name='Tel1')),
                ('tel2', models.CharField(blank=True, max_length=15, verbose_name='Tel2')),
                ('tel3', models.CharField(blank=True, max_length=15, verbose_name='Tel3')),
                ('nombre_corto', models.CharField(blank=True, help_text='(Display name) Dejar en blanco para autogenerar', max_length=10, verbose_name='Nombre Corto')),
                ('localization', models.CharField(choices=[('es_PA', 'Español PA'), ('en_US', 'Inglés EEUU')], default='es_PA', max_length=5, verbose_name='Localización')),
                ('foto', models.ImageField(blank=True, default='images/profiles/no_image_user.png', upload_to='images/profiles', verbose_name='Foto')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('bio', ckeditor.fields.RichTextField(null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('cia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_x_cia', to='core.cia', verbose_name='Cia Predeterminada')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': (('view_crm_module', 'Access to CRM Module'), ('view_sales_module', 'Access to Sales Module'), ('view_purchase_module', 'Access to Purchase Module'), ('view_inv_module', 'Access to Inventory Module'), ('view_hr_module', 'Access to HR Module'), ('view_accounting_module', 'Access to Accounting Module'), ('view_logistics_module', 'Access to Logistics Module'), ('view_linabi_module', 'Access to BI Module'), ('view_sys_module', 'Access to System Module')),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
