# Generated by Django 3.1.7 on 2021-06-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistaconfig',
            name='ordinal',
            field=models.IntegerField(default=0, help_text='Para ordenar las llaves de configuración', verbose_name='Ordinal'),
        ),
    ]
