# Generated by Django 3.1.7 on 2021-06-18 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vistaconfig_ordinal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vistaconfig',
            options={'ordering': ['vista', 'ordinal'], 'verbose_name': 'Configuración por Vista', 'verbose_name_plural': 'Configuraciones por Vista'},
        ),
    ]
