# Generated by Django 3.1.2 on 2020-11-30 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201016_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='cia',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cia', verbose_name='Cia Padre'),
        ),
    ]
