# Generated by Django 3.1.7 on 2021-06-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210617_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulo',
            options={'permissions': (('acc_crm', 'Access to CRM Module'), ('acc_sales', 'Access to Sales Module'), ('acc_purchase', 'Access to Purchase Module'), ('acc_inv', 'Access to Inventory Module'), ('acc_hr', 'Access to HR Module'), ('acc_accounting', 'Access to Accounting Module'), ('acc_logistics', 'Access to Logistics Module'), ('acc_linabi', 'Access to BI Module'), ('acc_config', 'Access to Configuration Module')), 'verbose_name': 'Módulo', 'verbose_name_plural': 'Módulos'},
        ),
        migrations.AlterModelOptions(
            name='vista',
            options={'permissions': (('acc_linabi_catalog', 'Access to LinaBI Catalog view'), ('acc_linabi_saledocs_master', 'Access to LinaBI Sale Docs Master view'), ('acc_linabi_saledocs_datail', 'Access to LinaBI Sale Docs Detail view'), ('acc_linabi_sales_detail', 'Access to LinaBI  Sales Detail view')), 'verbose_name': 'Vista', 'verbose_name_plural': 'Vistas'},
        ),
        migrations.AddField(
            model_name='vista',
            name='no_checkelperms',
            field=models.BooleanField(default=True, help_text='No evaluar permisos para elementos de la vista', verbose_name='No Evaluar Permisos'),
        ),
    ]
