# Generated by Django 3.1.2 on 2020-12-01 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cia_padre'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la secuencia', max_length=15, unique=True, verbose_name='Nombre')),
                ('conteo', models.IntegerField(default=0, help_text='Cuenta de la secuencia', verbose_name='Conteo')),
                ('obs', models.CharField(blank=True, max_length=25, null=True, verbose_name='Observación')),
            ],
            options={
                'verbose_name': 'Secuencia',
                'verbose_name_plural': 'Secuencias',
                'db_table': 'lina_core_gensequence',
            },
        ),
        migrations.CreateModel(
            name='TipoGenerico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('idgenerico', models.CharField(help_text='Identificador para propósitos generales', max_length=1, unique=True, verbose_name='ID Genérico')),
                ('descripcion', models.CharField(blank=True, default='', max_length=15, verbose_name='Descripción')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipogenerico_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipogenerico_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Tipo Generico',
                'verbose_name_plural': 'Tipos Genericos',
                'db_table': 'lina_core_tipo_generico',
                'ordering': ['idgenerico'],
            },
        ),
    ]
