# Generated by Django 3.1.7 on 2021-06-19 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210618_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vista',
            options={'permissions': (('acc_linabi_catalog', 'Access to LinaBI Catalog view'), ('acc_linabi_saledocs_master', 'Access to LinaBI Sale Docs Master view'), ('acc_linabi_saledocs_datail', 'Access to LinaBI Sale Docs Detail view'), ('acc_linabi_sales_detail', 'Access to LinaBI  Sales Detail view'), ('acc_linabi_reports', 'Access to LinaBI  Reports view')), 'verbose_name': 'Vista', 'verbose_name_plural': 'Vistas'},
        ),
    ]
