# Generated by Django 3.1.2 on 2020-12-01 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_gensequence_tipogenerico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_crm_module', 'Access to CRM Module'), ('view_sales_module', 'Access to Sales Module'), ('view_purchase_module', 'Access to Purchase Module'), ('view_inv_module', 'Access to Inventory Module'), ('view_hr_module', 'Access to HR Module'), ('view_accounting_module', 'Access to Accounting Module'), ('view_logistics_module', 'Access to Logistics Module'), ('view_linabi_module', 'Access to BI Module'), ('view_sys_module', 'Access to System Module'), ('view_module_crm', 'Access to CRM Module'), ('view_module_sales', 'Access to Sales Module'), ('view_module_purchase', 'Access to Purchase Module'), ('view_module_inv', 'Access to Inventory Module'), ('view_module_hr', 'Access to HR Module'), ('view_module_accounting', 'Access to Accounting Module'), ('view_module_logistics', 'Access to Logistics Module'), ('view_module_linabi', 'Access to BI Module'), ('view_module_sys', 'Access to System Module'))},
        ),
        migrations.CreateModel(
            name='StakeHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('codigo', models.CharField(help_text='Código Interno', max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Nombre')),
                ('ruc', models.CharField(blank=True, default='', max_length=30, verbose_name='RUC')),
                ('dv', models.CharField(blank=True, default='', max_length=2, verbose_name='DV')),
                ('direccion', models.TextField(blank=True, default='', max_length=100, verbose_name='Dirección')),
                ('tel1', models.CharField(blank=True, default='', max_length=15, verbose_name='Teléfono1')),
                ('tel2', models.CharField(blank=True, default='', max_length=15, verbose_name='Teléfono2')),
                ('tel3', models.CharField(blank=True, default='', max_length=15, verbose_name='Teléfono3')),
                ('email', models.EmailField(blank=True, default='', max_length=100, verbose_name='Email')),
                ('tipo', models.CharField(choices=[('N', 'Natural'), ('J', 'Jurídica')], default='N', max_length=1, verbose_name='Tipo')),
                ('cred', models.BooleanField(blank=True, default=False, help_text='Indica si es de tipo crédito', verbose_name='Crédito')),
                ('exonerado', models.BooleanField(blank=True, default=False, help_text='Exonerado de impuestos', verbose_name='Exonerado')),
                ('ordencompra', models.BooleanField(blank=True, default=False, help_text='Requerir orden de compra', verbose_name='Orden Compra')),
                ('diascr', models.DecimalField(choices=[(15, '15 días'), (30, '30 días'), (45, '45 días'), (60, '60 días'), (90, '90 días'), (120, '120 días')], decimal_places=0, default=30, help_text='Días de Crédito', max_digits=3, verbose_name='Días CR')),
                ('maxcr', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Máximo crédito otorgado', max_digits=12, verbose_name='Max CR')),
                ('contacto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contacto')),
                ('descauto', models.DecimalField(blank=True, decimal_places=3, default=0.0, help_text='Aplicar descuento en porciento de forma automática', max_digits=6, verbose_name='Descuento Automático')),
                ('retencion', models.DecimalField(blank=True, decimal_places=3, default=0.0, help_text='Porcentaje a retener', max_digits=6)),
                ('is_cli', models.BooleanField(blank=True, default=False, help_text='Es cliente', verbose_name='Cliente')),
                ('is_pro', models.BooleanField(blank=True, default=False, help_text='Es proveedor', verbose_name='Proveedor')),
                ('is_ban', models.BooleanField(blank=True, default=False, help_text='Es banco', verbose_name='Banco')),
                ('is_soc', models.BooleanField(blank=True, default=False, help_text='Es socio', verbose_name='Socio')),
                ('foto', models.ImageField(blank=True, default='images/profiles/no_image_user.png', upload_to='images/stakeholders', verbose_name='Foto')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('locale', models.CharField(choices=[('es_PA', 'Español PA'), ('en_US', 'Inglés EEUU')], default='es_PA', max_length=5, verbose_name='Localización')),
                ('website', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stakeholder_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('idgenerico', models.ForeignKey(help_text='Identificador para propósitos generales', on_delete=django.db.models.deletion.CASCADE, to='core.tipogenerico', verbose_name='ID Genérico')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stakeholder_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Stakeholder',
                'verbose_name_plural': 'Stakeholders',
                'db_table': 'lina_core_stakeholders',
                'permissions': (('view_cliente', 'View Customers details or list'), ('create_cliente', 'Create Customer'), ('update_cliente', 'Update Customer'), ('change_cliente_cr', 'Edit Customer Credit'), ('view_proveedor', 'View Provider details or list'), ('create_proveedor', 'Create Provider'), ('update_proveedor', 'Update Provider'), ('change_proveedor_cr', 'Edit Provider Credit'), ('view_banco', 'View Bank details or list'), ('create_banco', 'Create Bank'), ('update_banco', 'Update Bank'), ('view_socio', 'View Partner details or list'), ('create_socio', 'Create Partner'), ('update_socio', 'Update Partner')),
            },
        ),
    ]
