# Generated by Django 3.1.2 on 2020-12-01 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201130_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_module_crm', 'Access to CRM Module'), ('view_module_sales', 'Access to Sales Module'), ('view_module_purchase', 'Access to Purchase Module'), ('view_module_inv', 'Access to Inventory Module'), ('view_module_hr', 'Access to HR Module'), ('view_module_accounting', 'Access to Accounting Module'), ('view_module_logistics', 'Access to Logistics Module'), ('view_module_linabi', 'Access to BI Module'), ('view_module_sys', 'Access to System Module'))},
        ),
    ]
