# Generated by Django 3.1.7 on 2021-06-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210619_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vista',
            name='no_checkelperms',
        ),
        migrations.AddField(
            model_name='vista',
            name='checkelperms',
            field=models.BooleanField(default=True, help_text='Evaluar permisos para elementos de la vista', verbose_name='Evaluar Permisos'),
        ),
    ]
