# Generated by Django 3.1.2 on 2020-12-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201130_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stakeholder',
            options={'permissions': (('view_cliente', 'View customers details or list'), ('create_cliente', 'Create customer'), ('update_cliente', 'Update customer'), ('change_cliente_cr', 'Edit customer credit'), ('view_proveedor', 'View supplier details or list'), ('create_proveedor', 'Create supplier'), ('update_proveedor', 'Update supplier'), ('change_proveedor_cr', 'Edit supplier credit'), ('view_banco', 'View bank details or list'), ('create_banco', 'Create bank'), ('update_banco', 'Update bank'), ('view_socio', 'View partner details or list'), ('create_socio', 'Create partner'), ('update_socio', 'Update partner')), 'verbose_name': 'Stakeholder', 'verbose_name_plural': 'Stakeholders'},
        ),
        migrations.AlterField(
            model_name='tipogenerico',
            name='idgenerico',
            field=models.CharField(help_text='Identificador para propósitos generales', max_length=3, unique=True, verbose_name='ID Genérico'),
        ),
    ]
