# Generated by Django 3.1.6 on 2021-02-24 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201130_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='Nombre')),
                ('descrip', models.CharField(blank=True, max_length=50, verbose_name='Descripción')),
                ('tipo', models.PositiveIntegerField(default=0, verbose_name='Tipo')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modulo_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modulo_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'db_table': 'core_modulos',
            },
        ),
        migrations.CreateModel(
            name='Vista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='Nombre')),
                ('descrip', models.CharField(blank=True, max_length=50, verbose_name='Descripción')),
                ('link', models.CharField(default='/', max_length=100, verbose_name='Enlace Interno')),
                ('tipo', models.PositiveIntegerField(default=0, verbose_name='Tipo')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vista_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vista_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistas_x_modulo', to='core.modulo', verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Vista',
                'verbose_name_plural': 'Vistas',
                'db_table': 'core_vistas',
            },
        ),
        migrations.CreateModel(
            name='VistaConfigUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('configkey', models.CharField(max_length=20)),
                ('configval1', models.CharField(blank=True, max_length=20)),
                ('configval2', models.CharField(blank=True, max_length=20)),
                ('tipo', models.CharField(blank=True, max_length=10)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vistaconfiguser_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vistaconfiguser_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistaconfigs_x_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('vista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confuser_x_vista', to='core.vista', verbose_name='Vista')),
            ],
            options={
                'verbose_name': 'Configuración por Vista',
                'verbose_name_plural': 'Configuraciones por Vista',
                'db_table': 'core_vistaconfiguser',
            },
        ),
        migrations.CreateModel(
            name='VistaConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('configkey', models.CharField(max_length=20)),
                ('configval1', models.CharField(blank=True, max_length=20)),
                ('configval2', models.CharField(blank=True, max_length=20)),
                ('tipo', models.CharField(blank=True, max_length=10)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vistaconfig_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vistaconfig_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('vista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs_x_vista', to='core.vista', verbose_name='Vista')),
            ],
            options={
                'verbose_name': 'Configuración por Vista',
                'verbose_name_plural': 'Configuraciones por Vista',
                'db_table': 'core_vistaconfig',
            },
        ),
    ]
