# Generated by Django 3.1.6 on 2021-03-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210223_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vistaconfiguser',
            options={'verbose_name': 'Configuración por Vista y Usuario', 'verbose_name_plural': 'Configuraciones por Vista y Usuario'},
        ),
        migrations.AddField(
            model_name='vistaconfig',
            name='configval3',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vistaconfig',
            name='configval4',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vistaconfig',
            name='configval5',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vistaconfiguser',
            name='configval3',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vistaconfiguser',
            name='configval4',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vistaconfiguser',
            name='configval5',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
