# Generated by Django 3.1.6 on 2021-03-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210312_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistaconfig',
            name='configval6',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vistaconfig',
            name='configval7',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vistaconfig',
            name='configval8',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vistaconfig',
            name='configval9',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vistaconfiguser',
            name='configval6',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vistaconfiguser',
            name='configval7',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vistaconfiguser',
            name='configval8',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vistaconfiguser',
            name='configval9',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
