# Generated by Django 3.1.6 on 2021-03-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210313_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, default='images/profiles/no_image_user.png', null=True, upload_to='images/profiles', verbose_name='Foto'),
        ),
    ]
