# Generated by Django 3.1.7 on 2021-05-18 21:25

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210330_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='disponible',
            field=models.BooleanField(default=False, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, default='images/profiles/no_image_user.png', null=True, upload_to=apps.core.models.img_profile_path, verbose_name='Foto'),
        ),
    ]
