# Generated by Django 3.1.7 on 2021-06-05 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0014_auto_20210518_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='Nombre')),
                ('descrip', models.CharField(blank=True, max_length=50, verbose_name='Descripción')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vistaelement_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vistaelement_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Elemento',
                'verbose_name_plural': 'Elementos',
                'db_table': 'core_vistaelement',
            },
        ),
        migrations.AddField(
            model_name='vista',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.CreateModel(
            name='VistaElementAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesso', models.BooleanField(default=True, verbose_name='Acceso')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_x_group', to='auth.group', verbose_name='Grupo')),
                ('vista_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_x_vistaelelemt', to='core.vistaelement', verbose_name='Elemento_de_Vista')),
            ],
            options={
                'verbose_name': 'Acceso',
                'verbose_name_plural': 'Accesos',
                'db_table': 'core_vistaelementacc',
            },
        ),
        migrations.AddField(
            model_name='vistaelement',
            name='vista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements_x_vista', to='core.vista', verbose_name='Vista'),
        ),
    ]
