# Generated by Django 3.1.7 on 2021-06-05 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210604_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='modified_by',
        ),
    ]
