# Generated by Django 3.1.7 on 2021-06-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210605_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='disponible',
        ),
        migrations.AddField(
            model_name='modulo',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
    ]
