# Generated by Django 3.1.7 on 2021-06-05 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210605_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vistaelement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vistaelement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vistaelement',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='vistaelement',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='vistaelement',
            name='modified_by',
        ),
        migrations.AlterField(
            model_name='vistaelementaccess',
            name='vista_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_x_vistaelelemt', to='core.vistaelement', verbose_name='Elemento_de_Vista'),
        ),
    ]
