#!/bin/bash

set -o errexit
set -o nounset

worker_ready() {
    celery -A linapi inspect ping
}

until worker_ready; do
  >&2 echo 'Celery workers not available'
  sleep 1
done
>&2 echo 'Celery workers is available'

celery -A linapi  \
    --broker="${CELERY_BROKER}" \
    flower
    --port=5555 \