# Generated by Django 3.1.6 on 2021-02-20 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BICatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('REFERENCIA', models.CharField(max_length=30)),
                ('DESCRIP', models.CharField(max_length=100)),
                ('DESCRIP_EN', models.CharField(max_length=100)),
                ('UMEDIDA', models.CharField(max_length=100)),
                ('UMMULTIPLO', models.IntegerField()),
                ('TALLA', models.CharField(max_length=100)),
                ('PRECIOPUBLICO', models.FloatField(max_length=100)),
                ('PRECIO', models.FloatField(max_length=100)),
                ('CATEGORIA', models.CharField(max_length=100)),
                ('SUBCATEGORIA', models.CharField(max_length=100)),
                ('BODEGA', models.CharField(max_length=100)),
                ('FISICO', models.CharField(max_length=100)),
                ('RESERVA_BODEGA', models.CharField(max_length=100)),
                ('DISPONIBLE_REAL', models.CharField(max_length=100)),
                ('TRANSITO', models.CharField(max_length=100)),
                ('AFUTURO', models.CharField(max_length=100)),
                ('PREVENTA', models.CharField(max_length=100)),
                ('EMPAQUE', models.CharField(max_length=100)),
                ('PESO', models.FloatField(max_length=100)),
                ('CUBICAJE', models.FloatField(max_length=100)),
                ('MARCA', models.CharField(max_length=100)),
                ('CLA1', models.CharField(max_length=100)),
                ('CLA2', models.CharField(max_length=100)),
                ('CLA3', models.CharField(max_length=100)),
                ('COLORES', models.CharField(max_length=100)),
                ('DISTRIBUCION', models.CharField(max_length=100)),
                ('TEXTURA_NOM', models.CharField(max_length=100)),
                ('BARCODE', models.CharField(max_length=100)),
                ('PAISORIGEN', models.CharField(max_length=100)),
                ('NO_ENTRADA', models.CharField(max_length=100)),
                ('PROPIEDADES', models.CharField(max_length=100)),
                ('DEPARTAMENTO', models.CharField(max_length=100)),
                ('CLASI6_NOM', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BIFavorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Nombre')),
                ('link', models.CharField(max_length=200, unique=True, verbose_name='Enlace')),
                ('link_url', models.URLField(unique=True, verbose_name='Enlace URL')),
                ('descrip', models.TextField(blank=True, verbose_name='Descripción')),
                ('todos', models.BooleanField(default=True, verbose_name='Todos')),
                ('image', models.ImageField(blank=True, default='images/bifavoritos/prev1.jpg', upload_to='images/bifavoritos', verbose_name='Imagen')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bifavorito_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bifavorito_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'db_table': 'linabi_favorito',
            },
        ),
    ]
