# Generated by Django 3.1.7 on 2021-06-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linabi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bixlsxtemplatecol',
            name='orden',
        ),
        migrations.AddField(
            model_name='bixlsxtemplatecol',
            name='ordinal',
            field=models.IntegerField(default=0, verbose_name='Ordinal'),
        ),
    ]
