# Generated by Django 3.1.6 on 2021-02-24 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linabi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bifavorito',
            name='link_url',
        ),
    ]
