# Generated by Django 3.1.7 on 2021-06-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linabi', '0002_auto_20210617_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='bifavorito',
            name='perm',
            field=models.CharField(blank=True, help_text='Permiso de acceso relacionado', max_length=50, verbose_name='Permiso'),
        ),
    ]
