# Generated by Django 3.1.6 on 2021-03-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linabi', '0002_remove_bifavorito_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bifavorito',
            name='vuextore',
            field=models.CharField(blank=True, max_length=50, verbose_name='Vuex Store'),
        ),
    ]
