from django.db import models

attrs_catalog = {
    'ID': models.IntegerField(),
    'REFERENCIA': models.CharField(max_length=30),
    'DESCRIP': models.CharField(max_length=100),
    'DESCRIP_EN': models.CharField(max_length=100),
	'UMEDIDA': models.CharField(max_length=100),
    'UMMULTIPLO': models.IntegerField(),
    'TALLA': models.CharField(max_length=100),
    'PRECIOPUBLICO': models.FloatField(max_length=100),
    'PRECIO': models.FloatField(max_length=100),
    'DEPARTAMENTO': models.CharField(max_length=100),
    'CATEGORIA': models.CharField(max_length=100),
    'SUBCATEGORIA': models.CharField(max_length=100),
    'BODEGA': models.CharField(max_length=100),
	'FISICO': models.CharField(max_length=100),
	'RESERVA_BODEGA': models.CharField(max_length=100),
	'DISPONIBLE_REAL': models.CharField(max_length=100),
	'TRANSITO': models.CharField(max_length=100),
	'AFUTURO': models.CharField(max_length=100),
	'PREVENTA': models.CharField(max_length=100),
	'EMPAQUE': models.CharField(max_length=100),
	'PESO': models.FloatField(max_length=100),
	'CUBICAJE': models.FloatField(max_length=100),
	'MARCA': models.CharField(max_length=100),
	'CLA1': models.CharField(max_length=100),
	'CLA2': models.CharField(max_length=100),
	'CLA3': models.CharField(max_length=100),
	'COLORES': models.CharField(max_length=100),
	'DISTRIBUCION': models.CharField(max_length=100),
	'TEXTURA_NOM': models.CharField(max_length=100),
	'BARCODE': models.CharField(max_length=100),
	'PAISORIGEN': models.CharField(max_length=100),
	'NO_ENTRADA': models.CharField(max_length=100),
	'PROPIEDADES': models.CharField(max_length=100),
	'DEPARTAMENTO': models.CharField(max_length=100),
	'CLASI6_NOM': models.CharField(max_length=100),
    '__module__': 'apps.linabi.models'
}
