FROM python:latest
LABEL maintainer="Numentec"
ENV PYTHONUNBUFFERED 1
RUN mkdir linabe
WORKDIR /linabe
COPY requirements.txt /linabe/

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
COPY . .

RUN python manage.py makemigrations
RUN python manage.py migrate --fake